### PR TITLE
Add test_assets, cases, and one big JSON suite for the "Question/Answer Pair" tests. 

### PR DESCRIPTION
**Pull request by sierra-moxon**
I think we're also calling these "pass/fail" tests.   I generated these via a script in the TranslatorTestingModel repo as a short-term solution to our deadline tomorrow, but I'm wondering if we don't want those methods to live in pypi and the assets/cases/suites to be regenerated (based on the spreadsheet) every so often versus stored here?  

If we keep the Q/A pairs in a spreadsheet -- I would love to see the spreadsheet enforce the model interactively - @RichardBruskiewich and I could work together to generate a [Data Harmonizer](https://github.com/cidgoh/DataHarmonizer) instance that would enforce the schema in a spreadsheet interface :)

### CODE REVIEW

**Review by maximusunc — CHANGES_REQUESTED** [review]
I think there is still some misalignment on what test assets look like and how they're referenced by the test cases and suites. I was imagining assets being tsv files that come straight from SMEs/SMuRFs which are then converted in JSON test cases and suites. But we should discuss.

**Comment by sierra-moxon** [comment]
@maximusunc - what is the change requested here then?  just that assets are TSV? (cases and suite are also here, as JSON).

**Comment by maximusunc** [comment]
Right. I could imagine some sort of github workflow on-commit that validates any new test assets being added.

**Comment by RichardBruskiewich** [comment]
> I think there is still some misalignment on what test assets look like and how they're referenced by the test cases and suites. I was imagining assets being tsv files that come straight from SMEs/SMuRFs which are then converted in JSON test cases and suites. But we should discuss.

Hi @maximusunc, in response to your observation, I make the following points:

1. In principle, I do agree with your point that test assets can reside in a worksheet rather than JSON. In fact, the LinkML foundations of the **TranslatorTestingModel** support that as an option.  That said, I also do support @sierra-moxon's idea of embracing a structured worksheet data curation environment like the **DataHarmonizer**, as one of the possible adapted applications in the proposed  _"Test Documentation"_  toolkit.
2. We may retrieve **`TestAsset`** specifications from other non-worksheet sources, such as TAQA feedback issues. It is interesting to ponder how best to shepherd these into the system and what intermediate format within the Tests repository will be convenient for persisting these.
3. Looking more closely at the **`TestCase`** model, you'll note that each **`TestCase`** wraps its associated **`TestAsset`** instances directly inside, with all the same fields as a bare **`TestAsset`** (e.g. in JSON format).  This fact alone may remove reduce the need to keep the **`TestAsset`** entries stored separately in JSON format in the **Tests** repo since the code can, in principle, do the necessary embedding of the worksheet **`TestAsset`** entries into instances of **`TestCase`**, loaded directly from a worksheet (e.g. TSV) format.

**Comment by RichardBruskiewich** [comment]
@maximusunc (cc: @sierra-moxon), I suggest that we can just approve Sierra's initial PR as a pure data push of some helpful demo data, but keep up the dialog about the direction that things ought to move. As Andrew Su even realized, we are at a relatively early stage of the testing infrastructure, although we've made significant progress over the past month, and will continue to do so until the end of this project fiscal year, leading into the winter Relay. So... Onward Ho!

**Review by RichardBruskiewich — APPROVED** [review]

**Review by maximusunc — APPROVED** [review]
I agree. Let's get this in and keep the train running!

**Pull request merged**
