### PR TITLE
regenerated test cases with new schema

### PR DESCRIPTION
**Pull request by sierra-moxon**
Note from Sandrine: the ids are not persistent yet, they have changed between this PR and the last insert. 

From the testing meeting this week: we would like the test ids to be persistent, we are working on solutions to help keep them consistent (e.g. Data Harmonizer instance deployed in the model repo), but keeping ids consistent and persistent is still a WIP.

### CODE REVIEW

**Comment by sierra-moxon** [comment]
it looks like the schema changed - I fixed to include the new "test_metadata" inlined object that now contains that info (TestAsset.test_metadata.test_objective='AcceptanceTest'). 
I also grouped together assets into cases (now we only have 36 cases, and 300+ assets that group into those cases).  Benchmarks are still TestCases (with that additional test_metadata property set to "QuantitativeTest" - (TestAsset.test_metadata.test_objective='QuantitativeTest'))

**Comment by maximusunc** [comment]
I'm trying to run these with the Test Harness and have collected a few issues/comments:
- Some test assets have no `test_metadata` field. This won't be as big a deal once the `test_objective` gets moved to the TestCase level.
- Now that we're combining a bunch of Test Assets with the same input id and predicate into Test Cases, maybe we can put those input ids and predicates as top level Test Case fields as well? Otherwise, I have to grab the input id and predicate from the first Test Asset and assume that all the other Assets are the same.
    - Same goes for `runner_settings`, as that informs the Runner what query template to use.
- Some Test Cases don't have the `test_assets` field.

**Comment by maximusunc** [comment]
Is the `test_case_source` guaranteed to be the same between all similar assets?

**Comment by sierra-moxon** [comment]
> Is the `test_case_source` guaranteed the same between all similar assets?

at the moment, yes, but in general no.

**Comment by sierra-moxon** [comment]
> I'm trying to run these with the Test Harness and have collected a few issues/comments:
> 
> * Some test assets have no `test_metadata` field. This won't be as big a deal once the `test_objective` gets moved to the TestCase level.

I made this required in the schema for assets, but broke apart the test_metadata class into its properties for the TestCase so that we just get test_case_objective in the TestCase object, e.g.:

```
{
    "id": "TestCase_19",
    "name": "what treats MONDO:0008251",
    "description": "retinol_treats_familial_pityriasis_rubra_pilaris; Alcohols_treats_familial_pityriasis_rubra_pilaris",
    "tags": [],
    "test_env": "ci",
    "query_type": null,
    "test_assets": [ ... ],
    "preconditions": [],
    "trapi_template": null,
    "components": [
        "ars"
    ],
    "test_case_objective": "AcceptanceTest",
    "test_case_source": null,
    "test_case_predicate_name": "treats",
    "test_case_predicate_id": "biolink:treats",
    "test_case_input_id": "MONDO:0008251",
    "test_case_runner_settings": [
        "inferred"
    ]
}
```

> * Now that we're combining a bunch of Test Assets with the same input id and predicate into Test Cases, maybe we can put those input ids and predicates as top level Test Case fields as well? Otherwise, I have to grab the input id and predicate from the first Test Asset and assume that all the other Assets are the same.

I added these properties to TestCase:
```
test_case_input_id
test_case_predicate_name
test_case_predicate_id 
```
>   
>   * Same goes for `runner_settings`, as that informs the Runner what query template to use.

I added `test_case_runner_settings` to TestCase

> * Some Test Cases don't have the `test_assets` field.

I don't find any of these in my script after fixes above, but please let me know if you find one.  I can change the schema to require this field, but I hesitate to do so because I am not sure all test cases will have assets?  (e.g. a benchmark does not have assets at the moment).

**Review by maximusunc — APPROVED** [review]
Looks good for MVP1!

**Pull request merged**
